services:
  postgres:
    image: postgres:16
    container_name: marketplace_db
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"